name: g105
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49529
title: g105
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9d9e99'
    - '#d1d1cf'
    - '#363833'
    - '#565b54'
    - '#7a8479'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.27026494592201944
  rhythmicContrast: 0.5465788576439232
purpose:
  - name: null
    item: null
    url: null
